const professions = [
  "Aeronautical Engineer",
  "AMO Physicist",
  "Application Engineer",
  "Application Scientist XRD",
  "Applied Physicist",
  "Assistant Teaching Specialist",
  "Associate",
  "Associate Research Scientist",
  "Associate Scientist",
  "Associate Staff Scientist",
  "CEO & CTO",
  "Computational Physicist",
  "Computer Scientist",
  "Data Scientist",
  "Director of Analytical Services",
  "Epitaxial Engineer",
  "Lab Manager",
  "Material Scientist",
  "MBE Production Growth Engineer",
  "Medical Physicist",
  "Modeling and Simulation Engineer/Analyst",
  "Optical Engineer",
  "PhD Researcher",
  "Photonics Engineer",
  "Physical Scientist",
  "Physicist",
  "Principal Physicist",
  "Principal Scientist",
  "Process Engineer",
  "Quantum Measurement Scientist",
  "R&D Engineer",
  "R&D Physicist",
  "R&D Scientist",
  "Research Assistant",
  "Research Associate",
  "Research Coordinator",
  "Research Engineer",
  "Research Physical Scientist",
  "Research Physicist",
  "Research Scientist",
  "Research Staff",
  "Research Technologist",
  "Scientific Data Analyst",
  "Scientific Director",
  "Scientific Software Engineer",
  "Scientist",
  "Scientist I",
  "Scientist III",
  "Senior Applied Physicist",
  "Senior Engineer",
  "Senior Magnetic Development Engineer",
  "Senior Physics Scientist",
  "Senior Professional Staff I",
  "Senior Research Associate",
  "Senior Scientist",
  "Senior Staff Engineer",
  "Senior Test Engineer",
  "Shull Fellow",
  "Staff Scientist",
  "Teaching Fellow",
  "Technical Staff",
  "Thin Film Coating Engineer",
];

module.exports = professions;